"id","estRows","task","access object","operator info"
"Projection_10","1.83","root","","gharchive_dev.github_events.actor_id, any_value(gharchive_dev.github_events.actor_login)->Column#38, Column#35"
"└─TopN_13","1.83","root","","Column#35:desc, offset:0, count:50"
"  └─TableReader_52","1.83","root","partition:push_event,pull_request_event,issues_event,pull_request_review_event","MppVersion: 1, data:ExchangeSender_51"
"    └─ExchangeSender_51","1.83","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─Projection_47","1.83","mpp[tiflash]","","Column#35, gharchive_dev.github_events.actor_id, gharchive_dev.github_events.actor_login"
"        └─HashAgg_48","1.83","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_id, funcs:sum(Column#44)->Column#35, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id, funcs:firstrow(Column#46)->gharchive_dev.github_events.actor_login"
"          └─ExchangeReceiver_50","1.83","mpp[tiflash]","",""
"            └─ExchangeSender_49","1.83","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.actor_id, collate: binary]"
"              └─HashAgg_22","1.83","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_id, funcs:count(1)->Column#44, funcs:firstrow(gharchive_dev.github_events.actor_login)->Column#46"
"                └─Selection_46","195.55","mpp[tiflash]","","in(gharchive_dev.github_events.type, ""PullRequestEvent"", ""IssuesEvent"", ""PullRequestReviewEvent"", ""PushEvent""), or(or(and(eq(gharchive_dev.github_events.type, ""PullRequestEvent""), eq(gharchive_dev.github_events.action, ""opened"")), and(eq(gharchive_dev.github_events.type, ""IssuesEvent""), eq(gharchive_dev.github_events.action, ""opened""))), or(and(eq(gharchive_dev.github_events.type, ""PullRequestReviewEvent""), eq(gharchive_dev.github_events.action, ""created"")), eq(gharchive_dev.github_events.type, ""PushEvent""))), regexp(gharchive_dev.github_events.actor_login, ""^(bot-.+|.+bot|.+\[bot\]|.+-bot-.+|robot-.+|.+-ci-.+|.+-ci|.+-testing|.+clabot.+|.+-gerrit|k8s-.+|.+-machine|.+-automation|github-.+|.+-github|.+-service|.+-builds|codecov-.+|.+teamcity.+|jenkins-.+|.+-jira-.+)$"")"
"                  └─TableFullScan_45","6349301992.00","mpp[tiflash]","table:ge","keep order:false, PartitionTableScan:true"
