"id","estRows","task","access object","operator info"
"Sort_9","3566.76","root","","Column#36, Column#37"
"└─Projection_11","3566.76","root","","minus(dayofweek(gharchive_dev.github_events.created_at), 1)->Column#36, hour(cast(gharchive_dev.github_events.created_at, time))->Column#37, Column#35"
"  └─HashAgg_26","3566.76","root","","group by:Column#48, Column#49, funcs:sum(Column#50)->Column#35, funcs:firstrow(Column#51)->gharchive_dev.github_events.created_at"
"    └─IndexLookUp_27","3566.76","root","partition:push_event",""
"      ├─IndexRangeScan_23(Build)","63493.02","cop[tikv]","table:github_events, index:index_ge_on_actor_login_type(actor_login, type)","range:[""dependabot[bot]"" ""PushEvent"",""dependabot[bot]"" ""PushEvent""], keep order:false"
"      └─HashAgg_14(Probe)","3566.76","cop[tikv]","","group by:hour(cast(gharchive_dev.github_events.created_at, time)), minus(dayofweek(gharchive_dev.github_events.created_at), 1), funcs:sum(gharchive_dev.github_events.push_distinct_size)->Column#50, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#51"
"        └─Selection_25","61088.48","cop[tikv]","","ge(gharchive_dev.github_events.event_year, 2019)"
"          └─TableRowIDScan_24","63493.02","cop[tikv]","table:github_events","keep order:false"
