"id","estRows","task","access object","operator info"
"Projection_103","6.51","root","","any_value(Column#123)->Column#126, Column#119"
"└─StreamAgg_105","6.51","root","","group by:Column#119, funcs:firstrow(Column#123)->Column#123, funcs:firstrow(Column#119)->Column#119"
"  └─Window_102","6.51","root","","count(gharchive_dev.github_events.actor_login)->Column#123 over(order by Column#119 range between unbounded preceding and current row)"
"    └─Sort_51","6.51","root","","Column#119"
"      └─TableReader_89","6.51","root","partition:all","MppVersion: 1, data:ExchangeSender_88"
"        └─ExchangeSender_88","6.51","mpp[tiflash]","","ExchangeType: PassThrough"
"          └─Projection_84","6.51","mpp[tiflash]","","Column#119, gharchive_dev.github_events.actor_login"
"            └─HashAgg_85","6.51","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_login, funcs:min(Column#130)->Column#119, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"              └─ExchangeReceiver_87","6.51","mpp[tiflash]","",""
"                └─ExchangeSender_86","6.51","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.actor_login, collate: utf8mb4_bin]"
"                  └─HashAgg_59","6.51","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_login, funcs:min(gharchive_dev.github_events.event_year)->Column#130"
"                    └─Selection_83","634.93","mpp[tiflash]","","regexp(gharchive_dev.github_events.actor_login, ""^(bot-.+|.+bot|.+\[bot\]|.+-bot-.+|robot-.+|.+-ci-.+|.+-ci|.+-testing|.+clabot.+|.+-gerrit|k8s-.+|.+-machine|.+-automation|github-.+|.+-github|.+-service|.+-builds|codecov-.+|.+teamcity.+|jenkins-.+|.+-jira-.+)$"")"
"                      └─TableFullScan_82","6349301992.00","mpp[tiflash]","table:ge","keep order:false, PartitionTableScan:true"
