"id","estRows","task","access object","operator info"
"Sort_9","50.00","root","","gharchive_dev.github_events.created_at:desc"
"└─Projection_11","50.00","root","","gharchive_dev.github_events.id, gharchive_dev.github_events.type, gharchive_dev.github_events.action, gharchive_dev.github_events.actor_id, gharchive_dev.github_events.actor_login, gharchive_dev.github_events.repo_id, gharchive_dev.github_events.repo_name, gharchive_dev.github_events.number, gharchive_dev.github_events.pr_merged, gharchive_dev.github_events.created_at"
"  └─Limit_13","50.00","root","","offset:0, count:50"
"    └─IndexLookUp_23","50.00","root","partition:push_event,create_event,pull_request_event,watch_event,issue_comment_event,issues_event,fork_event,pull_request_review_comment_event,pull_request_review_event,release_event",""
"      ├─IndexRangeScan_19(Build)","52.57","cop[tikv]","table:github_events, index:index_github_events_on_created_at(created_at)","range:[2023-09-03 14:37:10,2023-09-03 14:38:10], keep order:false"
"      └─Limit_22(Probe)","50.00","cop[tikv]","","offset:0, count:50"
"        └─Selection_21","50.00","cop[tikv]","","in(gharchive_dev.github_events.type, ""WatchEvent"", ""ForkEvent"", ""IssuesEvent"", ""PullRequestEvent"", ""PushEvent"", ""CreateEvent"", ""ReleaseEvent"", ""PullRequestReviewCommentEvent"", ""PullRequestReviewEvent"", ""IssueCommentEvent""), not(like(gharchive_dev.github_events.actor_login, ""%-bot"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92))"
"          └─TableRowIDScan_20","52.57","cop[tikv]","table:github_events","keep order:false"
