"id","estRows","task","access object","operator info"
"Projection_31","5.00","root","","gharchive_dev.github_users.id, gharchive_dev.github_users.login, Column#90, Column#87, Column#88, Column#89"
"└─Limit_38","5.00","root","","offset:0, count:5"
"  └─Projection_148","5.00","root","","Column#87, Column#88, Column#89, Column#90, gharchive_dev.github_users.id, gharchive_dev.github_users.login"
"    └─IndexJoin_156","5.00","root","","inner join, inner:TableReader_152, outer key:gharchive_dev.github_events.actor_id, inner key:gharchive_dev.github_users.id, equal cond:eq(gharchive_dev.github_events.actor_id, gharchive_dev.github_users.id)"
"      ├─Sort_160(Build)","5.00","root","","Column#90:desc"
"      │ └─TableReader_121","50076.30","root","partition:pull_request_event","MppVersion: 1, data:ExchangeSender_120"
"      │   └─ExchangeSender_120","50076.30","mpp[tiflash]","","ExchangeType: PassThrough"
"      │     └─Projection_116","50076.30","mpp[tiflash]","","Column#87, Column#88, Column#89, Column#90, gharchive_dev.github_events.actor_id"
"      │       └─HashAgg_117","50076.30","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_id, funcs:count(distinct Column#134)->Column#87, funcs:count(distinct Column#135)->Column#88, funcs:count(distinct Column#136)->Column#89, funcs:sum(Column#137)->Column#90, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id"
"      │         └─ExchangeReceiver_119","50076.30","mpp[tiflash]","",""
"      │           └─ExchangeSender_118","50076.30","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.actor_id, collate: binary]"
"      │             └─HashAgg_83","50076.30","mpp[tiflash]","","group by:Column#144, Column#145, Column#146, Column#147, funcs:count(1)->Column#137"
"      │               └─Projection_162","5358349.78","mpp[tiflash]","","gharchive_dev.github_events.actor_id, case(eq(gharchive_dev.github_events.action, opened), gharchive_dev.github_events.pr_or_issue_id)->Column#145, case(and(eq(gharchive_dev.github_events.action, closed), eq(gharchive_dev.github_events.pr_merged, 0)), gharchive_dev.github_events.pr_or_issue_id)->Column#146, case(and(eq(gharchive_dev.github_events.action, closed), eq(gharchive_dev.github_events.pr_merged, 1)), gharchive_dev.github_events.pr_or_issue_id)->Column#147"
"      │                 └─HashJoin_70","5358349.78","mpp[tiflash]","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"      │                   ├─ExchangeReceiver_66(Build)","6.00","mpp[tiflash]","",""
"      │                   │ └─ExchangeSender_65","6.00","mpp[tiflash]","","ExchangeType: Broadcast"
"      │                   │   └─TableFullScan_64","6.00","mpp[tiflash]","table:blacklist_users","keep order:false, stats:pseudo"
"      │                   └─Selection_63(Probe)","6697937.23","mpp[tiflash]","","eq(gharchive_dev.github_events.type, ""PullRequestEvent""), gt(gharchive_dev.github_events.additions, 10), gt(gharchive_dev.github_events.created_at, 2023-09-02 14:50:54), not(istrue_with_null(regexp(gharchive_dev.github_events.actor_login, ""^(bot-.+|.+bot|.+\[bot\]|.+-bot-.+|robot-.+|.+-ci-.+|.+-ci|.+-testing|.+clabot.+|.+-gerrit|k8s-.+|.+-machine|.+-automation|.+-sdk|.+-integration|github-.+|.+-github|.+-service|.+-builds|codecov-.+|.+teamcity.+|jenkins-.+|.+-jira-.+|witness.+|.+witness|signcla.+|.+signcla|.+-cicd-.+|.+autotester.+)$""))), or(eq(gharchive_dev.github_events.action, ""opened""), eq(gharchive_dev.github_events.action, ""closed""))"
"      │                     └─TableFullScan_62","6349301992.00","mpp[tiflash]","table:ge","keep order:false, PartitionTableScan:true"
"      └─TableReader_152(Probe)","0.10","root","","data:Selection_151"
"        └─Selection_151","0.10","cop[tikv]","","gt(gharchive_dev.github_users.followers, 5)"
"          └─TableRangeScan_150","5.00","cop[tikv]","table:gu","range: decided by [gharchive_dev.github_events.actor_id], keep order:false"
