"id","estRows","task","access object","operator info"
"Sort_44","0.64","root","","Column#54:desc"
"└─Projection_46","0.64","root","","gharchive_dev.collections.id, gharchive_dev.collections.name, Column#54, gharchive_dev.collection_items.repo_id, gharchive_dev.collection_items.repo_name, Column#63, gharchive_dev.collection_items.last_month_rank, gharchive_dev.collection_items.last_2nd_month_rank, Column#60, Column#64"
"  └─Selection_47","0.64","root","","le(Column#63, 3)"
"    └─Window_48","0.80","root","","count(1)->Column#64 over(partition by gharchive_dev.collection_items.collection_id)"
"      └─Window_49","0.80","root","","row_number()->Column#63 over(partition by gharchive_dev.collection_items.collection_id order by Column#62 rows between current row and current row)"
"        └─Sort_153","0.80","root","","gharchive_dev.collection_items.collection_id, Column#62"
"          └─Projection_51","0.80","root","","gharchive_dev.collections.id, gharchive_dev.collections.name, Column#54, gharchive_dev.collection_items.repo_id, gharchive_dev.collection_items.repo_name, gharchive_dev.collection_items.last_month_rank, gharchive_dev.collection_items.last_2nd_month_rank, minus(gharchive_dev.collection_items.last_2nd_month_rank, gharchive_dev.collection_items.last_month_rank)->Column#60, gharchive_dev.collection_items.collection_id, ifnull(gharchive_dev.collection_items.last_month_rank, 999999)->Column#62"
"            └─Projection_52","0.80","root","","gharchive_dev.collection_items.collection_id, gharchive_dev.collection_items.repo_name, gharchive_dev.collection_items.repo_id, gharchive_dev.collection_items.last_month_rank, gharchive_dev.collection_items.last_2nd_month_rank, Column#54, gharchive_dev.collections.id, gharchive_dev.collections.name"
"              └─HashJoin_53","0.80","root","","inner join, equal:[eq(gharchive_dev.collections.id, Column#55)]"
"                ├─Sort_121(Build)","0.80","root","","Column#54:desc"
"                │ └─Projection_123","0.80","root","","cast(json_extract(gharchive_dev.stats_api_requests.query, $.collectionId), bigint(22) BINARY)->Column#55, Column#54"
"                │   └─Selection_124","0.80","root","","not(isnull(cast(json_extract(gharchive_dev.stats_api_requests.query, ""$.collectionId""), bigint(22) BINARY)))"
"                │     └─HashAgg_138","1.00","root","","group by:Column#94, funcs:count(Column#95)->Column#54, funcs:firstrow(Column#96)->gharchive_dev.stats_api_requests.query"
"                │       └─IndexLookUp_139","1.00","root","partition:P_LT_2023-09-01,P_LT_2023-10-01,P_LT_2023-11-01,P_LT_2023-12-01,P_LT_2024-01-01,P_LT_2024-02-01,P_LT_2024-03-01,P_LT_2024-04-01,P_LT_2024-05-01,P_LT_2024-06-01,P_LT_2024-07-01,P_LT_2024-08-01,P_LT_2024-09-01,P_LT_2024-10-01,P_LT_2024-11-01,P_LT_2024-12-01,P_LT_2025-01-01",""
"                │         ├─IndexRangeScan_135(Build)","13573.01","cop[tikv]","table:stats_api_requests, index:idx_sar_on_path(path)","range:[""/q/collection-"",""/q/collection.""), keep order:false"
"                │         └─HashAgg_126(Probe)","1.00","cop[tikv]","","group by:cast(json_extract(gharchive_dev.stats_api_requests.query, ""$.collectionId""), bigint(22) BINARY), funcs:count(1)->Column#95, funcs:firstrow(gharchive_dev.stats_api_requests.query)->Column#96"
"                │           └─Selection_137","13573.01","cop[tikv]","","gt(gharchive_dev.stats_api_requests.finished_at, 2023-08-03 14:36:24)"
"                │             └─TableRowIDScan_136","13573.01","cop[tikv]","table:stats_api_requests","keep order:false"
"                └─HashJoin_81(Probe)","79.00","root","","inner join, equal:[eq(gharchive_dev.collection_items.collection_id, gharchive_dev.collections.id)]"
"                  ├─IndexReader_120(Build)","83.00","root","","index:IndexFullScan_119"
"                  │ └─IndexFullScan_119","83.00","cop[tikv]","table:c, index:index_collections_on_name(name)","keep order:false"
"                  └─TableReader_103(Probe)","79.00","root","","data:Selection_102"
"                    └─Selection_102","79.00","cop[tikv]","","not(isnull(gharchive_dev.collection_items.collection_id))"
"                      └─TableFullScan_101","79.00","cop[tikv]","table:ci","keep order:false"
