"id","estRows","task","access object","operator info"
"Projection_14","36.80","root","","gharchive_dev.osdb_repos.group_name, Column#39"
"└─Sort_16","36.80","root","","Column#39:desc"
"  └─TableReader_76","36.80","root","partition:watch_event","MppVersion: 1, data:ExchangeSender_75"
"    └─ExchangeSender_75","36.80","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─Projection_71","36.80","mpp[tiflash]","","Column#39, gharchive_dev.osdb_repos.group_name"
"        └─HashAgg_72","36.80","mpp[tiflash]","","group by:gharchive_dev.osdb_repos.group_name, funcs:count(distinct gharchive_dev.github_events.actor_login)->Column#39, funcs:firstrow(gharchive_dev.osdb_repos.group_name)->gharchive_dev.osdb_repos.group_name"
"          └─ExchangeReceiver_74","36.80","mpp[tiflash]","",""
"            └─ExchangeSender_73","36.80","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.osdb_repos.group_name, collate: utf8mb4_bin]"
"              └─HashAgg_20","36.80","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_login, gharchive_dev.osdb_repos.group_name, "
"                └─Projection_70","770.88","mpp[tiflash]","","gharchive_dev.github_events.actor_login, gharchive_dev.osdb_repos.group_name"
"                  └─HashJoin_60","770.88","mpp[tiflash]","","inner join, equal:[eq(Column#43, Column#42)]"
"                    ├─ExchangeReceiver_31(Build)","46.00","mpp[tiflash]","",""
"                    │ └─ExchangeSender_30","46.00","mpp[tiflash]","","ExchangeType: Broadcast"
"                    │   └─Projection_28","46.00","mpp[tiflash]","","gharchive_dev.osdb_repos.group_name, cast(gharchive_dev.osdb_repos.id, double BINARY)->Column#43"
"                    │     └─TableFullScan_29","46.00","mpp[tiflash]","table:db","keep order:false, stats:pseudo"
"                    └─Projection_32(Probe)","377832945.71","mpp[tiflash]","","gharchive_dev.github_events.actor_login, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#42"
"                      └─Selection_34","377832945.71","mpp[tiflash]","","eq(gharchive_dev.github_events.type, ""WatchEvent"")"
"                        └─TableFullScan_33","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
