"id","estRows","task","access object","operator info"
"Sort_6","886.22","root","","Column#10:desc"
"└─TableReader_51","886.22","root","","MppVersion: 1, data:ExchangeSender_50"
"  └─ExchangeSender_50","886.22","mpp[tiflash]","","ExchangeType: PassThrough"
"    └─Projection_9","886.22","mpp[tiflash]","","gharchive_dev.stats_index_summary.table_name, gharchive_dev.stats_index_summary.index_name, Column#9, Column#10"
"      └─Projection_46","886.22","mpp[tiflash]","","Column#9, Column#10, gharchive_dev.stats_index_summary.table_name, gharchive_dev.stats_index_summary.index_name"
"        └─HashAgg_47","886.22","mpp[tiflash]","","group by:gharchive_dev.stats_index_summary.index_name, gharchive_dev.stats_index_summary.table_name, funcs:count(distinct gharchive_dev.stats_index_summary.digest)->Column#9, funcs:sum(Column#19)->Column#10, funcs:firstrow(gharchive_dev.stats_index_summary.table_name)->gharchive_dev.stats_index_summary.table_name, funcs:firstrow(gharchive_dev.stats_index_summary.index_name)->gharchive_dev.stats_index_summary.index_name"
"          └─ExchangeReceiver_49","886.22","mpp[tiflash]","",""
"            └─ExchangeSender_48","886.22","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.stats_index_summary.table_name, collate: utf8mb4_bin], [name: gharchive_dev.stats_index_summary.index_name, collate: utf8mb4_bin]"
"              └─HashAgg_44","886.22","mpp[tiflash]","","group by:Column#23, Column#24, Column#25, funcs:sum(Column#22)->Column#19"
"                └─Projection_54","1107.78","mpp[tiflash]","","cast(gharchive_dev.stats_index_summary.exec_count, decimal(20,0) UNSIGNED BINARY)->Column#22, gharchive_dev.stats_index_summary.table_name, gharchive_dev.stats_index_summary.index_name, gharchive_dev.stats_index_summary.digest"
"                  └─Selection_33","1107.78","mpp[tiflash]","","ge(gharchive_dev.stats_index_summary.summary_begin_time, 2023-09-03 00:00:00.000000), le(gharchive_dev.stats_index_summary.summary_end_time, 2023-09-03 23:59:59.000000)"
"                    └─TableFullScan_32","10000.00","mpp[tiflash]","table:sis","keep order:false, stats:pseudo"
