"id","estRows","task","access object","operator info"
"Sort_61","14429.47","root","","Column#189"
"└─Projection_63","14429.47","root","","gharchive_dev.github_events.repo_id, Column#189, Column#193"
"  └─Selection_65","14429.47","root","","eq(Column#192, 1)"
"    └─Window_67","18036.84","root","","sum(cast(Column#188, decimal(20,0) BINARY))->Column#193 over(partition by gharchive_dev.github_events.repo_id order by Column#189 range between unbounded preceding and current row)"
"      └─Window_68","18036.84","root","","row_number()->Column#192 over(partition by gharchive_dev.github_events.repo_id, Column#189 rows between current row and current row)"
"        └─Sort_124","18036.84","root","","gharchive_dev.github_events.repo_id, Column#189"
"          └─Projection_71","18036.84","root","","gharchive_dev.github_events.repo_id, date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#189, Column#188"
"            └─HashAgg_75","18036.84","root","","group by:Column#220, Column#221, funcs:count(1)->Column#188, funcs:firstrow(Column#218)->gharchive_dev.github_events.repo_id, funcs:firstrow(Column#219)->gharchive_dev.github_events.created_at"
"              └─Projection_149","302266.36","root","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.created_at, gharchive_dev.github_events.repo_id, date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#221"
"                └─Selection_79","302266.36","root","","eq(Column#184, 1)"
"                  └─Shuffle_97","377832.95","root","","execution info: concurrency:5, data sources:[IndexReader_95]"
"                    └─Window_82","377832.95","root","","row_number()->Column#184 over(partition by gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login rows between current row and current row)"
"                      └─Sort_96","472291.18","root","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login"
"                        └─IndexReader_95","472291.18","root","partition:watch_event","index:IndexRangeScan_94"
"                          └─IndexRangeScan_94","472291.18","cop[tikv]","table:github_events, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""WatchEvent"",41986369 ""WatchEvent""], keep order:false"
