"id","estRows","task","access object","operator info"
"Projection_12","7.50","root","","gharchive_dev.sys_repo_milestones.id, gharchive_dev.sys_repo_milestones.milestone_type_id, gharchive_dev.sys_repo_milestone_types.name, gharchive_dev.sys_repo_milestones.milestone_number, gharchive_dev.sys_repo_milestones.payload, gharchive_dev.sys_repo_milestones.reached_at"
"└─TopN_15","7.50","root","","gharchive_dev.sys_repo_milestones.reached_at:desc, offset:0, count:200"
"  └─Projection_20","7.50","root","","gharchive_dev.sys_repo_milestones.id, gharchive_dev.sys_repo_milestones.milestone_type_id, gharchive_dev.sys_repo_milestones.milestone_number, gharchive_dev.sys_repo_milestones.payload, gharchive_dev.sys_repo_milestones.reached_at, gharchive_dev.sys_repo_milestone_types.name"
"    └─IndexHashJoin_30","7.50","root","","inner join, inner:IndexLookUp_27, outer key:gharchive_dev.sys_repo_milestone_types.id, inner key:gharchive_dev.sys_repo_milestones.milestone_type_id, equal cond:eq(gharchive_dev.sys_repo_milestone_types.id, gharchive_dev.sys_repo_milestones.milestone_type_id)"
"      ├─TableReader_52(Build)","6.00","root","","data:TableFullScan_51"
"      │ └─TableFullScan_51","6.00","cop[tikv]","table:srmt","keep order:false, stats:pseudo"
"      └─IndexLookUp_27(Probe)","7.50","root","",""
"        ├─IndexRangeScan_25(Build)","7.50","cop[tikv]","table:srm, index:index_rm_on_repo_id_milestone_type_number(repo_id, milestone_type_id, milestone_number)","range: decided by [eq(gharchive_dev.sys_repo_milestones.milestone_type_id, gharchive_dev.sys_repo_milestone_types.id) eq(gharchive_dev.sys_repo_milestones.repo_id, 41986369)], keep order:false, stats:pseudo"
"        └─TableRowIDScan_26(Probe)","7.50","cop[tikv]","table:srm","keep order:false, stats:pseudo"
