"id","estRows","task","access object","operator info"
"Sort_27","452.49","root","","Column#110"
"└─Projection_29","452.49","root","","Column#110, Column#109, coalesce(Column#147, 0)->Column#149"
"  └─Projection_31","452.49","root","","Column#110, Column#109, Column#147"
"    └─HashJoin_35","452.49","root","","inner join, equal:[eq(Column#148, Column#110)]"
"      ├─Projection_60(Build)","452.49","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#148, Column#147"
"      │ └─Selection_62","452.49","root","","not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01"")))"
"      │   └─HashAgg_71","565.61","root","","group by:Column#167, funcs:count(Column#168)->Column#147, funcs:firstrow(Column#169)->gharchive_dev.github_events.created_at"
"      │     └─IndexReader_72","565.61","root","partition:issues_event","index:HashAgg_64"
"      │       └─HashAgg_64","565.61","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(gharchive_dev.github_events.number)->Column#168, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#169"
"      │         └─IndexRangeScan_70","12109.20","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""closed"",41986369 ""IssuesEvent"" ""closed""], keep order:false"
"      └─Projection_92(Probe)","616.38","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#110, Column#109"
"        └─Selection_94","616.38","root","","not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01"")))"
"          └─HashAgg_103","770.47","root","","group by:Column#188, funcs:count(Column#189)->Column#109, funcs:firstrow(Column#190)->gharchive_dev.github_events.created_at"
"            └─IndexReader_104","770.47","root","partition:issues_event","index:HashAgg_96"
"              └─HashAgg_96","770.47","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(gharchive_dev.github_events.number)->Column#189, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#190"
"                └─IndexRangeScan_102","16495.03","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"",41986369 ""IssuesEvent"" ""opened""], keep order:false"
