"id","estRows","task","access object","operator info"
"Projection_16","10.00","root","","gharchive_dev.db_repos.name, Column#38"
"└─TopN_20","10.00","root","","Column#38:desc, offset:0, count:10"
"  └─TableReader_92","10.00","root","partition:watch_event","MppVersion: 1, data:ExchangeSender_91"
"    └─ExchangeSender_91","10.00","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─TopN_90","10.00","mpp[tiflash]","","Column#38:desc, offset:0, count:10"
"        └─Projection_86","73.60","mpp[tiflash]","","Column#38, gharchive_dev.db_repos.name"
"          └─HashAgg_87","73.60","mpp[tiflash]","","group by:gharchive_dev.db_repos.name, funcs:count(distinct gharchive_dev.github_events.actor_login)->Column#38, funcs:firstrow(gharchive_dev.db_repos.name)->gharchive_dev.db_repos.name"
"            └─ExchangeReceiver_89","73.60","mpp[tiflash]","",""
"              └─ExchangeSender_88","73.60","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.db_repos.name, collate: utf8mb4_bin]"
"                └─HashAgg_84","73.60","mpp[tiflash]","","group by:gharchive_dev.db_repos.name, gharchive_dev.github_events.actor_login, "
"                  └─Projection_73","1541.76","mpp[tiflash]","","gharchive_dev.github_events.actor_login, gharchive_dev.db_repos.name"
"                    └─HashJoin_63","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#42, Column#41)]"
"                      ├─ExchangeReceiver_37(Build)","92.00","mpp[tiflash]","",""
"                      │ └─ExchangeSender_36","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"                      │   └─Projection_34","92.00","mpp[tiflash]","","gharchive_dev.db_repos.name, cast(gharchive_dev.db_repos.id, double BINARY)->Column#42"
"                      │     └─TableFullScan_35","92.00","mpp[tiflash]","table:db","keep order:false, stats:pseudo"
"                      └─Projection_38(Probe)","62074393.70","mpp[tiflash]","","gharchive_dev.github_events.actor_login, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#41"
"                        └─Selection_40","62074393.70","mpp[tiflash]","","eq(gharchive_dev.github_events.event_year, 2021), eq(gharchive_dev.github_events.type, ""WatchEvent"")"
"                          └─TableFullScan_39","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
