"id","estRows","task","access object","operator info"
"Projection_16","10.00","root","","gharchive_dev.db_repos.name, Column#38"
"└─TopN_20","10.00","root","","Column#38:desc, offset:0, count:10"
"  └─TableReader_94","10.00","root","partition:pull_request_event","MppVersion: 1, data:ExchangeSender_93"
"    └─ExchangeSender_93","10.00","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─TopN_92","10.00","mpp[tiflash]","","Column#38:desc, offset:0, count:10"
"        └─Projection_88","73.60","mpp[tiflash]","","Column#38, gharchive_dev.db_repos.name"
"          └─HashAgg_89","73.60","mpp[tiflash]","","group by:gharchive_dev.db_repos.name, funcs:sum(Column#49)->Column#38, funcs:firstrow(gharchive_dev.db_repos.name)->gharchive_dev.db_repos.name"
"            └─ExchangeReceiver_91","73.60","mpp[tiflash]","",""
"              └─ExchangeSender_90","73.60","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.db_repos.name, collate: utf8mb4_bin]"
"                └─HashAgg_86","73.60","mpp[tiflash]","","group by:gharchive_dev.db_repos.name, funcs:count(1)->Column#49"
"                  └─Projection_75","1541.76","mpp[tiflash]","","gharchive_dev.db_repos.name"
"                    └─HashJoin_65","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#42, Column#41)]"
"                      ├─ExchangeReceiver_39(Build)","92.00","mpp[tiflash]","",""
"                      │ └─ExchangeSender_38","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"                      │   └─Projection_36","92.00","mpp[tiflash]","","gharchive_dev.db_repos.name, cast(gharchive_dev.db_repos.id, double BINARY)->Column#42"
"                      │     └─TableFullScan_37","92.00","mpp[tiflash]","table:db_repos","keep order:false, stats:pseudo"
"                      └─Projection_40(Probe)","6133692.83","mpp[tiflash]","","cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#41"
"                        └─Selection_42","6133692.83","mpp[tiflash]","","eq(gharchive_dev.github_events.action, ""opened""), eq(gharchive_dev.github_events.event_year, 2021), eq(gharchive_dev.github_events.type, ""PullRequestEvent"")"
"                          └─TableFullScan_41","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
