"id","estRows","task","access object","operator info"
"Projection_102","10.00","root","","gharchive_dev.github_events.event_year, Column#340, Column#346"
"└─Sort_103","10.00","root","","gharchive_dev.github_events.event_year, Column#340"
"  └─Shuffle_211","10.00","root","","execution info: concurrency:5, data sources:[Sort_106]"
"    └─Window_105","10.00","root","","sum(cast(Column#341, decimal(20,0) BINARY))->Column#346 over(partition by Column#340 order by gharchive_dev.github_events.event_year range between unbounded preceding and current row)"
"      └─Sort_210","10.00","root","","Column#340, gharchive_dev.github_events.event_year"
"        └─Sort_106","10.00","root","","gharchive_dev.github_events.event_year, Column#340"
"          └─HashAgg_108","10.00","root","","group by:Column#340, gharchive_dev.github_events.event_year, funcs:count(1)->Column#341, funcs:firstrow(gharchive_dev.github_events.event_year)->gharchive_dev.github_events.event_year, funcs:firstrow(Column#340)->Column#340"
"            └─IndexHashJoin_116","167.58","root","","inner join, inner:IndexLookUp_113, outer key:gharchive_dev.github_events.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_events.repo_id)"
"              ├─Projection_119(Build)","10.00","root","","gharchive_dev.github_events.repo_id, any_value(gharchive_dev.db_repos.name)->Column#340"
"              │ └─TopN_123","10.00","root","","Column#339:desc, offset:0, count:10"
"              │   └─TableReader_202","10.00","root","partition:watch_event","MppVersion: 1, data:ExchangeSender_201"
"              │     └─ExchangeSender_201","10.00","mpp[tiflash]","","ExchangeType: PassThrough"
"              │       └─TopN_200","10.00","mpp[tiflash]","","Column#339:desc, offset:0, count:10"
"              │         └─Projection_195","1541.76","mpp[tiflash]","","Column#339, gharchive_dev.github_events.repo_id, gharchive_dev.db_repos.name"
"              │           └─HashAgg_193","1541.76","mpp[tiflash]","","group by:gharchive_dev.github_events.repo_id, funcs:count(distinct gharchive_dev.github_events.actor_login)->Column#339, funcs:firstrow(gharchive_dev.github_events.repo_id)->gharchive_dev.github_events.repo_id, funcs:firstrow(gharchive_dev.db_repos.name)->gharchive_dev.db_repos.name"
"              │             └─ExchangeReceiver_177","1541.76","mpp[tiflash]","",""
"              │               └─ExchangeSender_176","1541.76","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.repo_id, collate: binary]"
"              │                 └─Projection_175","1541.76","mpp[tiflash]","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login, gharchive_dev.db_repos.name"
"              │                   └─HashJoin_171","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#352, Column#351)]"
"              │                     ├─ExchangeReceiver_142(Build)","92.00","mpp[tiflash]","",""
"              │                     │ └─ExchangeSender_141","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"              │                     │   └─Projection_139","92.00","mpp[tiflash]","","gharchive_dev.db_repos.name, cast(gharchive_dev.db_repos.id, double BINARY)->Column#352"
"              │                     │     └─TableFullScan_140","92.00","mpp[tiflash]","table:repos","keep order:false, stats:pseudo"
"              │                     └─Projection_143(Probe)","377832945.71","mpp[tiflash]","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#351"
"              │                       └─Selection_145","377832945.71","mpp[tiflash]","","eq(gharchive_dev.github_events.type, ""WatchEvent"")"
"              │                         └─TableFullScan_144","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
"              └─IndexLookUp_113(Probe)","167.58","root","partition:watch_event",""
"                ├─IndexRangeScan_110(Build)","170.90","cop[tikv]","table:github_events, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_events.repo_id) eq(gharchive_dev.github_events.type, WatchEvent)], keep order:false"
"                └─Selection_112(Probe)","167.58","cop[tikv]","","le(gharchive_dev.github_events.event_year, 2021)"
"                  └─TableRowIDScan_111","170.90","cop[tikv]","table:github_events","keep order:false"
