"id","estRows","task","access object","operator info"
"Projection_20","10.00","root","","gharchive_dev.github_users.country_code, Column#65"
"└─TopN_23","10.00","root","","Column#65:desc, offset:0, count:10"
"  └─HashAgg_28","20.22","root","","group by:gharchive_dev.github_users.country_code, funcs:count(distinct gharchive_dev.github_events.actor_id)->Column#65, funcs:firstrow(gharchive_dev.github_users.country_code)->gharchive_dev.github_users.country_code"
"    └─IndexJoin_40","1541.76","root","","inner join, inner:IndexReader_39, outer key:gharchive_dev.github_events.actor_login, inner key:gharchive_dev.github_users.login, equal cond:eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_users.login)"
"      ├─TableReader_69(Build)","1541.76","root","partition:pull_request_event,issue_comment_event,issues_event,pull_request_review_comment_event,pull_request_review_event,commit_comment_event","MppVersion: 1, data:ExchangeSender_68"
"      │ └─ExchangeSender_68","1541.76","mpp[tiflash]","","ExchangeType: PassThrough"
"      │   └─HashJoin_65","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#69, Column#68)]"
"      │     ├─ExchangeReceiver_55(Build)","92.00","mpp[tiflash]","",""
"      │     │ └─ExchangeSender_54","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"      │     │   └─Projection_52","92.00","mpp[tiflash]","","cast(gharchive_dev.db_repos.id, double BINARY)->Column#69"
"      │     │     └─TableFullScan_53","92.00","mpp[tiflash]","table:db","keep order:false, stats:pseudo"
"      │     └─Projection_56(Probe)","231124175.98","mpp[tiflash]","","gharchive_dev.github_events.actor_id, gharchive_dev.github_events.actor_login, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#68"
"      │       └─Selection_58","231124175.98","mpp[tiflash]","","eq(gharchive_dev.github_events.event_year, 2021), in(gharchive_dev.github_events.type, ""IssuesEvent"", ""PullRequestEvent"", ""IssueCommentEvent"", ""PullRequestReviewCommentEvent"", ""CommitCommentEvent"", ""PullRequestReviewEvent"")"
"      │         └─TableFullScan_57","6349301992.00","mpp[tiflash]","table:ge","keep order:false, PartitionTableScan:true"
"      └─IndexReader_39(Probe)","1541.76","root","","index:Selection_38"
"        └─Selection_38","1541.76","cop[tikv]","","ne(gharchive_dev.github_users.country_code, """"), ne(gharchive_dev.github_users.country_code, ""N/A""), ne(gharchive_dev.github_users.country_code, ""UND"")"
"          └─IndexRangeScan_37","22579.24","cop[tikv]","table:gu, index:index_gu_on_login_is_bot_organization_country_code(login, is_bot, organization_formatted, country_code)","range: decided by [eq(gharchive_dev.github_users.login, gharchive_dev.github_events.actor_login)], keep order:false"
