"id","estRows","task","access object","operator info"
"Projection_16","1.00","root","","gharchive_dev.github_events.language, Column#38"
"└─TopN_19","1.00","root","","Column#38:desc, offset:0, count:5"
"  └─TableReader_83","1.00","root","partition:pull_request_event","MppVersion: 1, data:ExchangeSender_82"
"    └─ExchangeSender_82","1.00","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─Projection_78","1.00","mpp[tiflash]","","Column#38, gharchive_dev.github_events.language"
"        └─HashAgg_79","1.00","mpp[tiflash]","","group by:gharchive_dev.github_events.language, funcs:sum(Column#45)->Column#38, funcs:firstrow(gharchive_dev.github_events.language)->gharchive_dev.github_events.language"
"          └─ExchangeReceiver_81","1.00","mpp[tiflash]","",""
"            └─ExchangeSender_80","1.00","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.language, collate: utf8mb4_bin]"
"              └─HashAgg_28","1.00","mpp[tiflash]","","group by:gharchive_dev.github_events.language, funcs:count(1)->Column#45"
"                └─Projection_77","1541.76","mpp[tiflash]","","gharchive_dev.github_events.language"
"                  └─HashJoin_67","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#42, Column#41)]"
"                    ├─ExchangeReceiver_39(Build)","92.00","mpp[tiflash]","",""
"                    │ └─ExchangeSender_38","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"                    │   └─Projection_36","92.00","mpp[tiflash]","","cast(gharchive_dev.db_repos.id, double BINARY)->Column#42"
"                    │     └─TableFullScan_37","92.00","mpp[tiflash]","table:db","keep order:false, stats:pseudo"
"                    └─Projection_40(Probe)","6133692.83","mpp[tiflash]","","gharchive_dev.github_events.language, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#41"
"                      └─Selection_42","6133692.83","mpp[tiflash]","","eq(gharchive_dev.github_events.action, ""opened""), eq(gharchive_dev.github_events.event_year, 2021), eq(gharchive_dev.github_events.type, ""PullRequestEvent"")"
"                        └─TableFullScan_41","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
