"id","estRows","task","access object","operator info"
"Projection_16","20.00","root","","gharchive_dev.github_events.actor_login, Column#38"
"└─TopN_20","20.00","root","","Column#38:desc, offset:0, count:20"
"  └─TableReader_100","20.00","root","partition:pull_request_event","MppVersion: 1, data:ExchangeSender_99"
"    └─ExchangeSender_99","20.00","mpp[tiflash]","","ExchangeType: PassThrough"
"      └─TopN_98","20.00","mpp[tiflash]","","Column#38:desc, offset:0, count:20"
"        └─Projection_93","1541.76","mpp[tiflash]","","Column#38, gharchive_dev.github_events.actor_login"
"          └─HashAgg_91","1541.76","mpp[tiflash]","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#38, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"            └─ExchangeReceiver_75","1541.76","mpp[tiflash]","",""
"              └─ExchangeSender_74","1541.76","mpp[tiflash]","","ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: gharchive_dev.github_events.actor_login, collate: utf8mb4_bin]"
"                └─Projection_73","1541.76","mpp[tiflash]","","gharchive_dev.github_events.actor_login"
"                  └─HashJoin_69","1541.76","mpp[tiflash]","","inner join, equal:[eq(Column#42, Column#41)]"
"                    ├─ExchangeReceiver_41(Build)","92.00","mpp[tiflash]","",""
"                    │ └─ExchangeSender_40","92.00","mpp[tiflash]","","ExchangeType: Broadcast"
"                    │   └─Projection_38","92.00","mpp[tiflash]","","cast(gharchive_dev.db_repos.id, double BINARY)->Column#42"
"                    │     └─TableFullScan_39","92.00","mpp[tiflash]","table:db","keep order:false, stats:pseudo"
"                    └─Projection_42(Probe)","6133692.22","mpp[tiflash]","","gharchive_dev.github_events.actor_login, cast(gharchive_dev.github_events.repo_id, double BINARY)->Column#41"
"                      └─Selection_44","6133692.22","mpp[tiflash]","","eq(gharchive_dev.github_events.action, ""opened""), eq(gharchive_dev.github_events.event_year, 2021), eq(gharchive_dev.github_events.type, ""PullRequestEvent""), not(like(gharchive_dev.github_events.actor_login, ""%bot%"", 92))"
"                        └─TableFullScan_43","6349301992.00","mpp[tiflash]","table:github_events","keep order:false, PartitionTableScan:true"
