"id","estRows","task","access object","operator info"
"Projection_243","0.37","root","","Column#112, gharchive_dev.collection_items.repo_id, gharchive_dev.collection_items.repo_name, Column#95, Column#104"
"└─Window_245","0.37","root","","row_number()->Column#112 over(partition by Column#95 order by Column#104 desc rows between current row and current row)"
"  └─Sort_241","0.37","root","","Column#95, Column#104:desc"
"    └─Projection_70","0.37","root","","Column#95, Column#104, gharchive_dev.collection_items.repo_name, gharchive_dev.collection_items.repo_id"
"      └─MergeJoin_74","0.37","root","","inner join, left key:gharchive_dev.collection_items.repo_id, right key:gharchive_dev.github_events.repo_id"
"        ├─Selection_92(Build)","10.73","root","","eq(Column#103, 1)"
"        │ └─Window_94","13.41","root","","count(1)->Column#104 over(partition by gharchive_dev.github_events.repo_id order by Column#95 range between unbounded preceding and current row)"
"        │   └─Window_95","13.41","root","","row_number()->Column#103 over(partition by gharchive_dev.github_events.repo_id, Column#95 rows between current row and current row)"
"        │     └─Sort_211","13.41","root","","gharchive_dev.github_events.repo_id, Column#95"
"        │       └─Selection_100","13.41","root","","eq(Column#97, 1)"
"        │         └─Shuffle_210","16.76","root","","execution info: concurrency:5, data sources:[Projection_135]"
"        │           └─Window_103","16.76","root","","row_number()->Column#97 over(partition by gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login order by gharchive_dev.github_events.created_at rows between current row and current row)"
"        │             └─Sort_206","16.76","root","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.actor_login, gharchive_dev.github_events.created_at"
"        │               └─Projection_135","16.76","root","","gharchive_dev.github_events.repo_id, year(gharchive_dev.github_events.created_at)->Column#95, gharchive_dev.github_events.actor_login, gharchive_dev.github_events.created_at"
"        │                 └─IndexHashJoin_149","16.76","root","","inner join, inner:IndexReader_146, outer key:gharchive_dev.collection_items.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id)"
"        │                   ├─StreamAgg_169(Build)","1.00","root","","group by:gharchive_dev.collection_items.repo_id, funcs:firstrow(gharchive_dev.collection_items.repo_id)->gharchive_dev.collection_items.repo_id"
"        │                   │ └─IndexReader_160","0.46","root","","index:IndexRangeScan_159"
"        │                   │   └─IndexRangeScan_159","0.46","cop[tikv]","table:ci, index:index_ci_on_collection_id_repo_id(collection_id, repo_id)","range:[10001,10001], keep order:true"
"        │                   └─IndexReader_146(Probe)","16.76","root","partition:pull_request_event","index:IndexRangeScan_145"
"        │                     └─IndexRangeScan_145","16.76","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.collection_items.repo_id) eq(gharchive_dev.github_events.type, PullRequestEvent) eq(gharchive_dev.github_events.action, opened)], keep order:false"
"        └─Projection_91(Probe)","0.46","root","","gharchive_dev.collection_items.collection_id, gharchive_dev.collection_items.repo_name, gharchive_dev.collection_items.repo_id"
"          └─IndexLookUp_90","0.46","root","",""
"            ├─IndexRangeScan_88(Build)","0.46","cop[tikv]","table:ci, index:index_ci_on_collection_id_repo_id(collection_id, repo_id)","range:[10001,10001], keep order:true"
"            └─TableRowIDScan_89(Probe)","0.46","cop[tikv]","table:ci","keep order:false"
