"id","estRows","task","access object","operator info"
"Projection_49","10.73","root","","gharchive_dev.github_repos.repo_id, gharchive_dev.github_repos.repo_name, Column#96, Column#106"
"└─Sort_51","10.73","root","","Column#96"
"  └─IndexHashJoin_61","10.73","root","","left outer join, inner:TableReader_56, outer key:gharchive_dev.github_events.repo_id, inner key:gharchive_dev.github_repos.repo_id, equal cond:eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_repos.repo_id)"
"    ├─Selection_206(Build)","10.73","root","","eq(Column#105, 1)"
"    │ └─Window_208","13.41","root","","count(1)->Column#106 over(partition by gharchive_dev.github_events.repo_id order by Column#96 range between unbounded preceding and current row)"
"    │   └─Window_71","13.41","root","","row_number()->Column#105 over(partition by gharchive_dev.github_events.repo_id, Column#96 rows between current row and current row)"
"    │     └─Sort_187","13.41","root","","gharchive_dev.github_events.repo_id, Column#96"
"    │       └─Selection_76","13.41","root","","eq(Column#98, 1)"
"    │         └─Shuffle_186","16.76","root","","execution info: concurrency:5, data sources:[Projection_111]"
"    │           └─Window_79","16.76","root","","row_number()->Column#98 over(partition by gharchive_dev.github_events.repo_id, gharchive_dev.github_events.number order by gharchive_dev.github_events.created_at rows between current row and current row)"
"    │             └─Sort_182","16.76","root","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.number, gharchive_dev.github_events.created_at"
"    │               └─Projection_111","16.76","root","","gharchive_dev.github_events.repo_id, gharchive_dev.github_events.number, date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#96, gharchive_dev.github_events.created_at"
"    │                 └─IndexHashJoin_125","16.76","root","","inner join, inner:IndexReader_122, outer key:gharchive_dev.collection_items.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id)"
"    │                   ├─StreamAgg_145(Build)","1.00","root","","group by:gharchive_dev.collection_items.repo_id, funcs:firstrow(gharchive_dev.collection_items.repo_id)->gharchive_dev.collection_items.repo_id"
"    │                   │ └─IndexReader_136","0.46","root","","index:IndexRangeScan_135"
"    │                   │   └─IndexRangeScan_135","0.46","cop[tikv]","table:ci, index:index_ci_on_collection_id_repo_id(collection_id, repo_id)","range:[10001,10001], keep order:true"
"    │                   └─IndexReader_122(Probe)","16.76","root","partition:pull_request_event","index:IndexRangeScan_121"
"    │                     └─IndexRangeScan_121","16.76","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.collection_items.repo_id) eq(gharchive_dev.github_events.type, PullRequestEvent)], keep order:false"
"    └─TableReader_56(Probe)","10.73","root","","data:TableRangeScan_55"
"      └─TableRangeScan_55","10.73","cop[tikv]","table:gr","range: decided by [gharchive_dev.github_events.repo_id], keep order:false"
