"id","estRows","task","access object","operator info"
"Sort_202","0.37","root","","Column#151"
"└─Projection_204","0.37","root","","gharchive_dev.collection_items.repo_id, gharchive_dev.collection_items.repo_name, 2023-08->Column#161, 2023-07->Column#162, Column#149, Column#151, ifnull(Column#158, 0)->Column#163, Column#160, mul(div(cast(minus(Column#149, Column#158), decimal(20,0) BINARY), cast(Column#158, decimal(20,0) BINARY)), 100)->Column#164, minus(Column#151, Column#160)->Column#165, Column#136"
"  └─HashJoin_206","0.37","root","","left outer join, equal:[eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_events.repo_id)]"
"    ├─Projection_207(Build)","0.37","root","","Column#136, gharchive_dev.collection_items.repo_name, gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id, Column#149, Column#151"
"    │ └─HashJoin_209","0.37","root","","inner join, equal:[eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_events.repo_id)]"
"    │   ├─HashJoin_224(Build)","0.37","root","","inner join, equal:[eq(gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id)]"
"    │   │ ├─IndexLookUp_365(Build)","0.37","root","",""
"    │   │ │ ├─IndexRangeScan_363(Build)","0.37","cop[tikv]","table:ci, index:index_collection_items_on_collection_id(collection_id)","range:[10001,10001], keep order:false"
"    │   │ │ └─TableRowIDScan_364(Probe)","0.37","cop[tikv]","table:ci","keep order:false"
"    │   │ └─HashAgg_281(Probe)","16.76","root","","group by:gharchive_dev.github_events.repo_id, funcs:count(distinct gharchive_dev.github_events.number)->Column#136, funcs:firstrow(gharchive_dev.github_events.repo_id)->gharchive_dev.github_events.repo_id"
"    │   │   └─IndexHashJoin_295","16.76","root","","inner join, inner:IndexReader_292, outer key:gharchive_dev.collection_items.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id)"
"    │   │     ├─StreamAgg_307(Build)","1.00","root","","group by:gharchive_dev.collection_items.repo_id, funcs:firstrow(gharchive_dev.collection_items.repo_id)->gharchive_dev.collection_items.repo_id"
"    │   │     │ └─IndexReader_279","0.46","root","","index:IndexRangeScan_278"
"    │   │     │   └─IndexRangeScan_278","0.46","cop[tikv]","table:ci, index:index_ci_on_collection_id_repo_id(collection_id, repo_id)","range:[10001,10001], keep order:true"
"    │   │     └─IndexReader_292(Probe)","16.76","root","partition:pull_request_event","index:IndexRangeScan_291"
"    │   │       └─IndexRangeScan_291","16.76","cop[tikv]","table:github_events, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.collection_items.repo_id) eq(gharchive_dev.github_events.type, PullRequestEvent)], keep order:false"
"    │   └─Selection_369(Probe)","8.58","root","","not(isnull(gharchive_dev.github_events.repo_id))"
"    │     └─Window_370","10.73","root","","row_number()->Column#151 over(order by Column#149 desc rows between current row and current row)"
"    │       └─Sort_374","10.73","root","","Column#149:desc"
"    │         └─Selection_372","10.73","root","","eq(Column#147, ""2023-08-01"")"
"    │           └─CTEFullScan_373","13.41","root","CTE:prs_group_by_month AS sgn","data:CTE_1"
"    └─Selection_375(Probe)","8.58","root","","not(isnull(gharchive_dev.github_events.repo_id))"
"      └─Window_376","10.73","root","","row_number()->Column#160 over(order by Column#158 desc rows between current row and current row)"
"        └─Sort_380","10.73","root","","Column#158:desc"
"          └─Selection_378","10.73","root","","eq(Column#156, ""2023-07-01"")"
"            └─CTEFullScan_379","13.41","root","CTE:prs_group_by_month AS sgn","data:CTE_1"
"CTE_1","13.41","root","","Non-Recursive CTE"
"└─Projection_71(Seed Part)","13.41","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#83, gharchive_dev.github_events.repo_id, Column#82"
"  └─Selection_73","13.41","root","","or(eq(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), ""2023-08-01""), eq(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), ""2023-07-01""))"
"    └─HashAgg_75","16.76","root","","group by:Column#209, Column#210, funcs:count(distinct Column#206)->Column#82, funcs:firstrow(Column#207)->gharchive_dev.github_events.created_at, funcs:firstrow(Column#208)->gharchive_dev.github_events.repo_id"
"      └─Projection_198","16.76","root","","gharchive_dev.github_events.number, gharchive_dev.github_events.created_at, gharchive_dev.github_events.repo_id, date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#209, gharchive_dev.github_events.repo_id"
"        └─IndexHashJoin_87","16.76","root","","inner join, inner:IndexReader_84, outer key:gharchive_dev.collection_items.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.collection_items.repo_id, gharchive_dev.github_events.repo_id)"
"          ├─StreamAgg_126(Build)","1.00","root","","group by:gharchive_dev.collection_items.repo_id, funcs:firstrow(gharchive_dev.collection_items.repo_id)->gharchive_dev.collection_items.repo_id"
"          │ └─IndexReader_117","0.46","root","","index:IndexRangeScan_116"
"          │   └─IndexRangeScan_116","0.46","cop[tikv]","table:ci, index:index_ci_on_collection_id_repo_id(collection_id, repo_id)","range:[10001,10001], keep order:true"
"          └─IndexReader_84(Probe)","16.76","root","partition:pull_request_event","index:IndexRangeScan_83"
"            └─IndexRangeScan_83","16.76","cop[tikv]","table:github_events, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.collection_items.repo_id) eq(gharchive_dev.github_events.type, PullRequestEvent) eq(gharchive_dev.github_events.action, opened) lt(gharchive_dev.github_events.created_at, 2023-09-01 00:00:00.000000) ge(gharchive_dev.github_events.created_at, 2023-07-01 00:00:00.000000)], keep order:false"
