"id","estRows","task","access object","operator info"
"Sort_107","20.22","root","","Column#67:desc"
"└─Projection_109","20.22","root","","gharchive_dev.github_users.country_code, Column#67, div(cast(Column#67, decimal(20,0) BINARY), Column#71)->Column#72"
"  └─HashJoin_110","20.22","root","","CARTESIAN inner join"
"    ├─StreamAgg_114(Build)","1.00","root","","funcs:sum(Column#92)->Column#71"
"    │ └─Projection_119","20.22","root","","cast(Column#70, decimal(20,0) BINARY)->Column#92"
"    │   └─CTEFullScan_116","20.22","root","CTE:group_by_area","data:CTE_0"
"    └─CTEFullScan_112(Probe)","20.22","root","CTE:group_by_area","data:CTE_0"
"CTE_0","20.22","root","","Non-Recursive CTE"
"└─Projection_20(Seed Part)","20.22","root","","gharchive_dev.github_users.country_code, Column#62"
"  └─HashAgg_22","20.22","root","","group by:gharchive_dev.github_users.country_code, funcs:count(distinct gharchive_dev.github_events.actor_login)->Column#62, funcs:firstrow(gharchive_dev.github_users.country_code)->gharchive_dev.github_users.country_code"
"    └─IndexJoin_32","13196.03","root","","inner join, inner:IndexReader_31, outer key:gharchive_dev.github_events.actor_login, inner key:gharchive_dev.github_users.login, equal cond:eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_users.login)"
"      ├─IndexReader_64(Build)","16495.03","root","partition:issues_event","index:IndexRangeScan_63"
"      │ └─IndexRangeScan_63","16495.03","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"",41986369 ""IssuesEvent"" ""opened""], keep order:false"
"      └─IndexReader_31(Probe)","16495.03","root","","index:Selection_30"
"        └─Selection_30","16495.03","cop[tikv]","","ne(gharchive_dev.github_users.country_code, """"), ne(gharchive_dev.github_users.country_code, ""N/A""), ne(gharchive_dev.github_users.country_code, ""UND""), not(isnull(gharchive_dev.github_users.country_code))"
"          └─IndexRangeScan_29","241571.31","cop[tikv]","table:gu, index:index_gu_on_login_is_bot_organization_country_code(login, is_bot, organization_formatted, country_code)","range: decided by [eq(gharchive_dev.github_users.login, gharchive_dev.github_events.actor_login)], keep order:false"
