"id","estRows","task","access object","operator info"
"Sort_14","150.82","root","","Column#57:desc"
"└─Projection_16","150.82","root","","any_value(gharchive_dev.github_events.creator_user_id)->Column#58, gharchive_dev.github_events.creator_user_login, Column#57"
"  └─HashAgg_19","150.82","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(1)->Column#57, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login, funcs:firstrow(gharchive_dev.github_events.creator_user_id)->gharchive_dev.github_events.creator_user_id"
"    └─IndexHashJoin_35","150.82","root","","inner join, inner:IndexLookUp_32, outer key:gharchive_dev.github_repos.repo_id, inner key:gharchive_dev.github_events.repo_id, equal cond:eq(gharchive_dev.github_repos.repo_id, gharchive_dev.github_events.repo_id)"
"      ├─IndexReader_70(Build)","9.00","root","","index:IndexRangeScan_69"
"      │ └─IndexRangeScan_69","9.00","cop[tikv]","table:gr, index:index_gr_on_owner_login_repo_id_created_at(owner_login, repo_id, created_at)","range:[""chaos-mesh"",""chaos-mesh""], [""pingcap"",""pingcap""], [""tikv"",""tikv""], keep order:false"
"      └─IndexLookUp_32(Probe)","150.82","root","partition:pull_request_event",""
"        ├─Selection_31(Build)","150.82","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"        │ └─IndexRangeScan_29","5582.74","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range: decided by [eq(gharchive_dev.github_events.repo_id, gharchive_dev.github_repos.repo_id) eq(gharchive_dev.github_events.type, PullRequestEvent) eq(gharchive_dev.github_events.action, closed)], keep order:false"
"        └─TableRowIDScan_30(Probe)","150.82","cop[tikv]","table:ge","keep order:false"
