"id","estRows","task","access object","operator info"
"Projection_20","2179.83","root","","Column#76, Column#80"
"└─Window_65","2179.83","root","","sum(cast(Column#75, decimal(20,0) BINARY))->Column#80 over(order by Column#76 range between unbounded preceding and current row)"
"  └─Sort_25","2179.83","root","","Column#76"
"    └─Projection_29","2179.83","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#76, Column#75"
"      └─HashAgg_38","2179.83","root","","group by:Column#91, funcs:count(Column#92)->Column#75, funcs:firstrow(Column#93)->gharchive_dev.github_events.created_at"
"        └─IndexReader_39","2179.83","root","partition:pull_request_event","index:HashAgg_31"
"          └─HashAgg_31","2179.83","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(1)->Column#92, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#93"
"            └─IndexRangeScan_37","46668.02","cop[tikv]","table:github_events, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""opened"",41986369 ""PullRequestEvent"" ""opened""], keep order:false"
