"id","estRows","task","access object","operator info"
"Projection_133","1.00","root","","Column#219, gharchive_dev.github_events.creator_user_login, Column#116, Column#198, Column#199, Column#217, Column#218"
"└─Limit_140","1.00","root","","offset:0, count:50"
"  └─Window_277","1.00","root","","row_number()->Column#219 over(order by Column#116 desc rows between current row and current row)"
"    └─Sort_276","1.00","root","","Column#116:desc"
"      └─Projection_143","1.00","root","","gharchive_dev.github_events.creator_user_login, Column#116, coalesce(Column#155, 0)->Column#198, coalesce(minus(Column#116, Column#155), 0)->Column#199, div(cast(Column#116, decimal(20,0) BINARY), 283)->Column#217, case(isnull(gharchive_dev.github_events.creator_user_login), 1, 0)->Column#218"
"        └─HashJoin_145","1.00","root","","left outer join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.github_events.creator_user_login)]"
"          ├─HashJoin_146(Build)","1.00","root","","left outer join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.github_events.creator_user_login)]"
"          │ ├─Sort_149(Build)","1.00","root","","Column#155:desc"
"          │ │ └─HashAgg_153","1.00","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(1)->Column#155, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"          │ │   └─HashJoin_167","148.09","root","","anti semi join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.blacklist_users.login)]"
"          │ │     ├─IndexReader_193(Build)","6.00","root","","index:IndexFullScan_192"
"          │ │     │ └─IndexFullScan_192","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"          │ │     └─IndexLookUp_186(Probe)","185.11","root","partition:pull_request_event",""
"          │ │       ├─Selection_184(Build)","185.11","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"          │ │       │ └─IndexRangeScan_182","231.39","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" 2023-07-01 00:00:00,41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00), keep order:false"
"          │ │       └─Selection_185(Probe)","185.11","cop[tikv]","","not(like(gharchive_dev.github_events.creator_user_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.creator_user_login, ""%bot"", 92))"
"          │ │         └─TableRowIDScan_183","185.11","cop[tikv]","table:ge","keep order:false"
"          │ └─CTEFullScan_148(Probe)","1.00","root","CTE:code_contribution_last_month AS lm","data:CTE_1"
"          └─HashAgg_216(Probe)","6.45","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"            └─HashJoin_230","1968.61","root","","anti semi join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.blacklist_users.login)]"
"              ├─IndexReader_256(Build)","6.00","root","","index:IndexFullScan_255"
"              │ └─IndexFullScan_255","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"              └─IndexLookUp_249(Probe)","2460.76","root","partition:pull_request_event",""
"                ├─Selection_247(Build)","2460.76","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"                │ └─IndexRangeScan_245","3075.95","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" -inf,41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00), keep order:false"
"                └─Selection_248(Probe)","2460.76","cop[tikv]","","not(like(gharchive_dev.github_events.creator_user_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.creator_user_login, ""%bot"", 92))"
"                  └─TableRowIDScan_246","2460.76","cop[tikv]","table:ge","keep order:false"
"CTE_1","1.00","root","","Non-Recursive CTE"
"└─Projection_54(Seed Part)","1.00","root","","gharchive_dev.github_events.creator_user_login, Column#73"
"  └─Sort_56","1.00","root","","Column#73:desc"
"    └─HashAgg_60","1.00","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(1)->Column#73, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"      └─HashJoin_74","148.09","root","","anti semi join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.blacklist_users.login)]"
"        ├─IndexReader_100(Build)","6.00","root","","index:IndexFullScan_99"
"        │ └─IndexFullScan_99","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"        └─IndexLookUp_93(Probe)","185.11","root","partition:pull_request_event",""
"          ├─Selection_91(Build)","185.11","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"          │ └─IndexRangeScan_89","231.39","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00,41986369 ""PullRequestEvent"" ""closed"" 2023-09-01 00:00:00), keep order:false"
"          └─Selection_92(Probe)","185.11","cop[tikv]","","not(like(gharchive_dev.github_events.creator_user_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.creator_user_login, ""%bot"", 92))"
"            └─TableRowIDScan_90","185.11","cop[tikv]","table:ge","keep order:false"
