"id","estRows","task","access object","operator info"
"Projection_143","27.04","root","","Column#220, gharchive_dev.github_events.actor_login, Column#116, Column#198, Column#199, Column#218, Column#219"
"└─Limit_150","27.04","root","","offset:0, count:50"
"  └─Window_307","27.04","root","","row_number()->Column#220 over(order by Column#116 desc rows between current row and current row)"
"    └─Sort_306","27.04","root","","Column#116:desc"
"      └─Projection_153","27.04","root","","gharchive_dev.github_events.actor_login, Column#116, coalesce(Column#155, 0)->Column#198, coalesce(minus(Column#116, Column#155), 0)->Column#199, div(cast(Column#116, decimal(20,0) BINARY), 284)->Column#218, case(isnull(gharchive_dev.github_events.actor_login), 1, 0)->Column#219"
"        └─HashJoin_155","27.04","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_events.actor_login)]"
"          ├─HashJoin_156(Build)","27.04","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_events.actor_login)]"
"          │ ├─Sort_159(Build)","27.04","root","","Column#155:desc"
"          │ │ └─HashAgg_163","27.04","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#155, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"          │ │   └─HashJoin_180","2639.21","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"          │ │     ├─IndexReader_203(Build)","6.00","root","","index:IndexFullScan_202"
"          │ │     │ └─IndexFullScan_202","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"          │ │     └─IndexReader_196(Probe)","4123.76","root","partition:issues_event","index:Selection_195"
"          │ │       └─Selection_195","4123.76","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"          │ │         └─IndexRangeScan_194","4123.76","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"" 2023-07-01 00:00:00,41986369 ""IssuesEvent"" ""opened"" 2023-08-01 00:00:00), keep order:false"
"          │ └─CTEFullScan_158(Probe)","27.04","root","CTE:issue_contribution_last_month AS lm","data:CTE_1"
"          └─HashAgg_236(Probe)","359.47","root","","group by:gharchive_dev.github_events.actor_login, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"            └─HashJoin_253","35083.83","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"              ├─IndexReader_276(Build)","6.00","root","","index:IndexFullScan_275"
"              │ └─IndexFullScan_275","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"              └─IndexReader_269(Probe)","54818.48","root","partition:issues_event","index:Selection_268"
"                └─Selection_268","54818.48","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"                  └─IndexRangeScan_267","54818.49","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"" -inf,41986369 ""IssuesEvent"" ""opened"" 2023-08-01 00:00:00), keep order:false"
"CTE_1","27.04","root","","Non-Recursive CTE"
"└─Projection_54(Seed Part)","27.04","root","","gharchive_dev.github_events.actor_login, Column#73"
"  └─Sort_56","27.04","root","","Column#73:desc"
"    └─HashAgg_60","27.04","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#73, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"      └─HashJoin_77","2639.21","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"        ├─IndexReader_100(Build)","6.00","root","","index:IndexFullScan_99"
"        │ └─IndexFullScan_99","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"        └─IndexReader_93(Probe)","4123.76","root","partition:issues_event","index:Selection_92"
"          └─Selection_92","4123.76","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"            └─IndexRangeScan_91","4123.76","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"" 2023-08-01 00:00:00,41986369 ""IssuesEvent"" ""opened"" 2023-09-01 00:00:00), keep order:false"
