"id","estRows","task","access object","operator info"
"Projection_55","8445.46","root","","Column#71, Column#72, div(cast(Column#72, decimal(20,0) BINARY), cast(Column#70, decimal(20,0) BINARY))->Column#73"
"└─TopN_58","8445.46","root","","Column#72:desc, offset:0, count:9999999999"
"  └─HashJoin_64","8445.46","root","","CARTESIAN inner join"
"    ├─HashAgg_65(Build)","1.00","root","","funcs:count(1)->Column#70"
"    │ └─CTEFullScan_67","10556.82","root","CTE:issue_creator_companies","data:CTE_0"
"    └─Selection_69(Probe)","8445.46","root","","ne(length(Column#71), 0), not(in(Column#71, ""-"", ""none"", ""no"", ""home"", ""n/a"", ""null"", ""unknown""))"
"      └─CTEFullScan_70","10556.82","root","CTE:issue_creator_companies AS sub","data:CTE_0"
"CTE_0","10556.82","root","","Non-Recursive CTE"
"└─Projection_24(Seed Part)","10556.82","root","","trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, ,, ), -, ), @, ), www., ), inc, ), .com, ), .cn, ), ., ))->Column#63, Column#62"
"  └─Selection_25","10556.82","root","","or(1, and(ne(length(trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, "","", """"), ""-"", """"), ""@"", """"), ""www."", """"), ""inc"", """"), "".com"", """"), "".cn"", """"), ""."", """"))), 0), not(in(trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, "","", """"), ""-"", """"), ""@"", """"), ""www."", """"), ""inc"", """"), "".com"", """"), "".cn"", """"), ""."", """")), ""-"", ""none"", ""no"", ""home"", ""n/a"", ""null"", ""unknown""))))"
"    └─HashAgg_26","13196.03","root","","group by:Column#100, funcs:count(distinct Column#98)->Column#62, funcs:firstrow(Column#99)->gharchive_dev.github_users.organization"
"      └─Projection_53","13196.03","root","","gharchive_dev.github_events.actor_login, gharchive_dev.github_users.organization, trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, ,, ), -, ), @, ), www., ), inc, ), .com, ), .cn, ), ., ))->Column#100"
"        └─IndexJoin_31","13196.03","root","","left outer join, inner:IndexLookUp_30, outer key:gharchive_dev.github_events.actor_login, inner key:gharchive_dev.github_users.login, equal cond:eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_users.login)"
"          ├─IndexReader_49(Build)","16495.03","root","partition:issues_event","index:IndexRangeScan_48"
"          │ └─IndexRangeScan_48","16495.03","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""opened"",41986369 ""IssuesEvent"" ""opened""], keep order:false"
"          └─IndexLookUp_30(Probe)","16495.03","root","",""
"            ├─IndexRangeScan_28(Build)","16495.03","cop[tikv]","table:u, index:index_gu_on_login_is_bot_organization_country_code(login, is_bot, organization_formatted, country_code)","range: decided by [eq(gharchive_dev.github_users.login, gharchive_dev.github_events.actor_login)], keep order:false"
"            └─TableRowIDScan_29(Probe)","16495.03","cop[tikv]","table:u","keep order:false"
