"id","estRows","task","access object","operator info"
"Projection_143","50.00","root","","Column#216, gharchive_dev.github_events.actor_login, Column#114, Column#194, Column#195, Column#214, Column#215"
"└─Limit_150","50.00","root","","offset:0, count:50"
"  └─Window_237","50.00","root","","row_number()->Column#216 over(order by Column#114 desc rows between current row and current row)"
"    └─Sort_236","4584.47","root","","Column#114:desc"
"      └─Projection_153","4584.47","root","","gharchive_dev.github_events.actor_login, Column#114, coalesce(Column#153, 0)->Column#194, coalesce(minus(Column#114, Column#153), 0)->Column#195, div(cast(Column#114, decimal(20,0) BINARY), 38)->Column#214, case(isnull(gharchive_dev.github_events.actor_login), 1, 0)->Column#215"
"        └─HashJoin_155","4584.47","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_events.actor_login)]"
"          ├─HashJoin_156(Build)","4584.47","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_events.actor_login)]"
"          │ ├─Sort_159(Build)","1.00","root","","Column#153:desc"
"          │ │ └─HashAgg_161","1.00","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#153, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"          │ │   └─TableDual_162","0.00","root","","rows:0"
"          │ └─CTEFullScan_158(Probe)","4584.47","root","CTE:code_contribution_last_month AS lm","data:CTE_1"
"          └─HashAgg_166(Probe)","60942.95","root","","group by:gharchive_dev.github_events.actor_login, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"            └─HashJoin_183","5947996.35","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"              ├─IndexReader_206(Build)","6.00","root","","index:IndexFullScan_205"
"              │ └─IndexFullScan_205","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"              └─IndexReader_199(Probe)","9293743.37","root","partition:push_event","index:Selection_198"
"                └─Selection_198","9293743.37","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"                  └─IndexRangeScan_197","9293744.30","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PushEvent"" """" -inf,41986369 ""PushEvent"" """" 2023-08-01 00:00:00), keep order:false"
"CTE_1","4584.47","root","","Non-Recursive CTE"
"└─Projection_54(Seed Part)","4584.47","root","","gharchive_dev.github_events.actor_login, Column#73"
"  └─Sort_56","4584.47","root","","Column#73:desc"
"    └─HashAgg_60","4584.47","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#73, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"      └─HashJoin_77","447442.05","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"        ├─IndexReader_100(Build)","6.00","root","","index:IndexFullScan_99"
"        │ └─IndexFullScan_99","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"        └─IndexReader_93(Probe)","699128.14","root","partition:push_event","index:Selection_92"
"          └─Selection_92","699128.14","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"            └─IndexRangeScan_91","699128.21","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PushEvent"" """" 2023-08-01 00:00:00,41986369 ""PushEvent"" """" 2023-09-01 00:00:00), keep order:false"
