"id","estRows","task","access object","operator info"
"Projection_126","50.00","root","","Column#129, gharchive_dev.github_events.actor_login, Column#80, Column#126, Column#127, Column#128"
"└─Limit_133","50.00","root","","offset:0, count:50"
"  └─Window_221","50.00","root","","row_number()->Column#129 over(order by Column#80 desc rows between current row and current row)"
"    └─Sort_220","81.05","root","","Column#80:desc"
"      └─Projection_136","81.05","root","","gharchive_dev.github_events.actor_login, Column#80, coalesce(Column#124, 0)->Column#126, coalesce(minus(Column#80, Column#124), 0)->Column#127, div(cast(Column#80, decimal(20,0) BINARY), Column#85)->Column#128"
"        └─HashJoin_137","81.05","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_events.actor_login)]"
"          ├─HashAgg_150(Build)","81.05","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#124, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"          │ └─HashJoin_167","7910.57","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"          │   ├─IndexReader_190(Build)","6.00","root","","index:IndexFullScan_189"
"          │   │ └─IndexFullScan_189","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"          │   └─IndexReader_183(Probe)","12360.27","root","partition:issue_comment_event","index:Selection_182"
"          │     └─Selection_182","12360.27","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"          │       └─IndexRangeScan_181","12360.27","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssueCommentEvent"" ""created"" 2023-07-01 00:00:00,41986369 ""IssueCommentEvent"" ""created"" 2023-08-01 00:00:00), keep order:false"
"          └─HashJoin_139(Probe)","81.05","root","","CARTESIAN inner join"
"            ├─Projection_142(Build)","1.00","root","","coalesce(Column#84, 0)->Column#85"
"            │ └─HashAgg_143","1.00","root","","funcs:sum(Column#162)->Column#84"
"            │   └─Projection_222","81.05","root","","cast(Column#83, decimal(20,0) BINARY)->Column#162"
"            │     └─CTEFullScan_145","81.05","root","CTE:issue_contribution_last_month","data:CTE_0"
"            └─CTEFullScan_141(Probe)","81.05","root","CTE:issue_contribution_last_month AS lm","data:CTE_0"
"CTE_0","81.05","root","","Non-Recursive CTE"
"└─Projection_42(Seed Part)","81.05","root","","gharchive_dev.github_events.actor_login, Column#37"
"  └─HashAgg_46","81.05","root","","group by:gharchive_dev.github_events.actor_login, funcs:count(1)->Column#37, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"    └─HashJoin_63","7910.57","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"      ├─IndexReader_86(Build)","6.00","root","","index:IndexFullScan_85"
"      │ └─IndexFullScan_85","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"      └─IndexReader_79(Probe)","12360.27","root","partition:issue_comment_event","index:Selection_78"
"        └─Selection_78","12360.27","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"          └─IndexRangeScan_77","12360.27","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssueCommentEvent"" ""created"" 2023-08-01 00:00:00,41986369 ""IssueCommentEvent"" ""created"" 2023-09-01 00:00:00), keep order:false"
