"id","estRows","task","access object","operator info"
"Projection_84","20.27","root","","gharchive_dev.github_events.actor_id, Column#74, Column#159, Column#75, Column#119, Column#120, Column#158"
"└─Limit_91","20.27","root","","offset:0, count:50"
"  └─Window_152","20.27","root","","row_number()->Column#159 over(order by Column#75 desc rows between current row and current row)"
"    └─Sort_151","20.27","root","","Column#75:desc"
"      └─Projection_94","20.27","root","","gharchive_dev.github_events.actor_id, Column#74, Column#75, coalesce(Column#113, 0)->Column#119, coalesce(minus(Column#75, Column#113), 0)->Column#120, div(cast(Column#75, decimal(20,0) BINARY), 1666)->Column#158"
"        └─HashJoin_95","20.27","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_id, gharchive_dev.github_events.actor_id)]"
"          ├─HashAgg_115(Build)","20.27","root","","group by:gharchive_dev.github_events.actor_id, funcs:count(Column#174)->Column#113, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id"
"          │ └─IndexLookUp_116","20.27","root","partition:pull_request_review_event",""
"          │   ├─IndexRangeScan_113(Build)","2710.70","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestReviewEvent"" ""created"" 2023-07-01 00:00:00,41986369 ""PullRequestReviewEvent"" ""created"" 2023-08-01 00:00:00), keep order:false"
"          │   └─HashAgg_99(Probe)","20.27","cop[tikv]","","group by:gharchive_dev.github_events.actor_id, funcs:count(1)->Column#174"
"          │     └─TableRowIDScan_114","2710.70","cop[tikv]","table:ge","keep order:false"
"          └─CTEFullScan_97(Probe)","20.27","root","CTE:review_contribution_last_month AS lm","data:CTE_0"
"CTE_0","20.27","root","","Non-Recursive CTE"
"└─Projection_23(Seed Part)","20.27","root","","gharchive_dev.github_events.actor_id, any_value(gharchive_dev.github_events.actor_login)->Column#36, Column#35"
"  └─HashAgg_39","20.27","root","","group by:gharchive_dev.github_events.actor_id, funcs:count(Column#138)->Column#35, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id, funcs:firstrow(Column#140)->gharchive_dev.github_events.actor_login"
"    └─IndexLookUp_40","20.27","root","partition:pull_request_review_event",""
"      ├─IndexRangeScan_37(Build)","2710.70","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestReviewEvent"" ""created"" 2023-08-01 00:00:00,41986369 ""PullRequestReviewEvent"" ""created"" 2023-09-01 00:00:00), keep order:false"
"      └─HashAgg_25(Probe)","20.27","cop[tikv]","","group by:gharchive_dev.github_events.actor_id, funcs:count(1)->Column#138, funcs:firstrow(gharchive_dev.github_events.actor_login)->Column#140"
"        └─TableRowIDScan_38","2710.70","cop[tikv]","table:ge","keep order:false"
