"id","estRows","task","access object","operator info"
"Projection_101","1.00","root","","Column#220, gharchive_dev.github_events.creator_user_login, Column#110, Column#188, Column#189, Column#218, Column#219"
"└─Limit_108","1.00","root","","offset:0, count:50"
"  └─Window_211","1.00","root","","row_number()->Column#220 over(order by Column#110 desc rows between current row and current row)"
"    └─Sort_210","1.00","root","","Column#110:desc"
"      └─Projection_111","1.00","root","","gharchive_dev.github_events.creator_user_login, Column#110, coalesce(Column#147, 0)->Column#188, coalesce(minus(Column#110, Column#147), 0)->Column#189, div(cast(Column#110, decimal(20,0) BINARY), 410)->Column#218, case(isnull(gharchive_dev.github_events.creator_user_login), 1, 0)->Column#219"
"        └─HashJoin_113","1.00","root","","left outer join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.github_events.creator_user_login)]"
"          ├─HashJoin_114(Build)","1.00","root","","left outer join, equal:[eq(gharchive_dev.github_events.creator_user_login, gharchive_dev.github_events.creator_user_login)]"
"          │ ├─Sort_117(Build)","1.00","root","","Column#147:desc"
"          │ │ └─HashAgg_133","1.00","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(Column#234)->Column#147, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"          │ │   └─IndexLookUp_134","1.00","root","partition:pull_request_event",""
"          │ │     ├─Selection_132(Build)","185.11","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"          │ │     │ └─IndexRangeScan_130","231.39","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" 2023-07-01 00:00:00,41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00), keep order:false"
"          │ │     └─HashAgg_120(Probe)","1.00","cop[tikv]","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(1)->Column#234"
"          │ │       └─TableRowIDScan_131","185.11","cop[tikv]","table:ge","keep order:false"
"          │ └─CTEFullScan_116(Probe)","1.00","root","CTE:code_contribution_last_month AS lm","data:CTE_1"
"          └─HashAgg_179(Probe)","8.06","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"            └─IndexLookUp_180","8.06","root","partition:pull_request_event",""
"              ├─Selection_178(Build)","2460.76","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"              │ └─IndexRangeScan_176","3075.95","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" -inf,41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00), keep order:false"
"              └─HashAgg_166(Probe)","8.06","cop[tikv]","","group by:gharchive_dev.github_events.creator_user_login, "
"                └─TableRowIDScan_177","2460.76","cop[tikv]","table:ge","keep order:false"
"CTE_1","1.00","root","","Non-Recursive CTE"
"└─Projection_39(Seed Part)","1.00","root","","gharchive_dev.github_events.creator_user_login, Column#69"
"  └─Sort_41","1.00","root","","Column#69:desc"
"    └─HashAgg_57","1.00","root","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(Column#204)->Column#69, funcs:firstrow(gharchive_dev.github_events.creator_user_login)->gharchive_dev.github_events.creator_user_login"
"      └─IndexLookUp_58","1.00","root","partition:pull_request_event",""
"        ├─Selection_56(Build)","185.11","cop[tikv]","","eq(gharchive_dev.github_events.pr_merged, 1)"
"        │ └─IndexRangeScan_54","231.39","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""PullRequestEvent"" ""closed"" 2023-08-01 00:00:00,41986369 ""PullRequestEvent"" ""closed"" 2023-09-01 00:00:00), keep order:false"
"        └─HashAgg_44(Probe)","1.00","cop[tikv]","","group by:gharchive_dev.github_events.creator_user_login, funcs:count(1)->Column#204"
"          └─TableRowIDScan_55","185.11","cop[tikv]","table:ge","keep order:false"
