"id","estRows","task","access object","operator info"
"Projection_122","18.11","root","","Column#154, gharchive_dev.github_events.actor_id, Column#78, Column#79, Column#125, Column#126, Column#153"
"└─Limit_129","18.11","root","","offset:0, count:50"
"  └─Window_214","18.11","root","","row_number()->Column#154 over(order by Column#79 desc rows between current row and current row)"
"    └─Sort_213","18.11","root","","Column#79:desc"
"      └─Projection_132","18.11","root","","gharchive_dev.github_events.actor_id, Column#78, Column#79, coalesce(Column#119, 0)->Column#125, coalesce(minus(Column#79, Column#119), 0)->Column#126, div(cast(Column#79, decimal(20,0) BINARY), 77)->Column#153"
"        └─HashJoin_133","18.11","root","","left outer join, equal:[eq(gharchive_dev.github_events.actor_id, gharchive_dev.github_events.actor_id)]"
"          ├─HashAgg_138(Build)","18.11","root","","group by:gharchive_dev.github_events.actor_id, funcs:count(1)->Column#119, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id"
"          │ └─HashJoin_155","1937.47","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"          │   ├─IndexReader_182(Build)","6.00","root","","index:IndexFullScan_181"
"          │   │ └─IndexFullScan_181","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"          │   └─IndexLookUp_175(Probe)","3027.30","root","partition:issues_event",""
"          │     ├─Selection_174(Build)","3027.30","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"          │     │ └─IndexRangeScan_172","3027.30","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""closed"" 2023-07-01 00:00:00,41986369 ""IssuesEvent"" ""closed"" 2023-08-01 00:00:00), keep order:false"
"          │     └─TableRowIDScan_173(Probe)","3027.30","cop[tikv]","table:ge","keep order:false"
"          └─CTEFullScan_135(Probe)","18.11","root","CTE:issue_contribution_last_month AS lm","data:CTE_0"
"CTE_0","18.11","root","","Non-Recursive CTE"
"└─Projection_32(Seed Part)","18.11","root","","gharchive_dev.github_events.actor_id, any_value(gharchive_dev.github_events.actor_login)->Column#38, Column#37"
"  └─HashAgg_35","18.11","root","","group by:gharchive_dev.github_events.actor_id, funcs:count(1)->Column#37, funcs:firstrow(gharchive_dev.github_events.actor_id)->gharchive_dev.github_events.actor_id, funcs:firstrow(gharchive_dev.github_events.actor_login)->gharchive_dev.github_events.actor_login"
"    └─HashJoin_52","1937.47","root","","anti semi join, equal:[eq(gharchive_dev.github_events.actor_login, gharchive_dev.blacklist_users.login)]"
"      ├─IndexReader_79(Build)","6.00","root","","index:IndexFullScan_78"
"      │ └─IndexFullScan_78","6.00","cop[tikv]","table:bu, index:blacklist_users_login_uindex(login)","keep order:false, stats:pseudo"
"      └─IndexLookUp_72(Probe)","3027.30","root","partition:issues_event",""
"        ├─Selection_71(Build)","3027.30","cop[tikv]","","not(like(gharchive_dev.github_events.actor_login, ""%[bot]"", 92)), not(like(gharchive_dev.github_events.actor_login, ""%bot"", 92))"
"        │ └─IndexRangeScan_69","3027.30","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""IssuesEvent"" ""closed"" 2023-08-01 00:00:00,41986369 ""IssuesEvent"" ""closed"" 2023-09-01 00:00:00), keep order:false"
"        └─TableRowIDScan_70(Probe)","3027.30","cop[tikv]","table:ge","keep order:false"
