"id","estRows","task","access object","operator info"
"Projection_56","241813.09","root","","Column#67, Column#68, div(cast(Column#68, decimal(20,0) BINARY), cast(Column#72, decimal(20,0) BINARY))->Column#73"
"└─TopN_59","241813.09","root","","Column#68:desc, offset:0, count:9999999999"
"  └─Projection_64","241813.09","root","","Column#67, Column#68, Column#72"
"    └─HashJoin_66","241813.09","root","","CARTESIAN inner join"
"      ├─HashAgg_67(Build)","1.00","root","","funcs:count(1)->Column#72"
"      │ └─CTEFullScan_69","302266.36","root","CTE:star_companies","data:CTE_0"
"      └─Selection_71(Probe)","241813.09","root","","ne(length(Column#67), 0), not(in(Column#67, ""-"", ""none"", ""no"", ""home"", ""n/a"", ""null"", ""unknown""))"
"        └─CTEFullScan_72","302266.36","root","CTE:star_companies","data:CTE_0"
"CTE_0","302266.36","root","","Non-Recursive CTE"
"└─Projection_24(Seed Part)","302266.36","root","","trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, ,, ), -, ), @, ), www., ), inc, ), .com, ), .cn, ), ., ))->Column#63, Column#62"
"  └─Selection_25","302266.36","root","","or(and(ne(length(trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, "","", """"), ""-"", """"), ""@"", """"), ""www."", """"), ""inc"", """"), "".com"", """"), "".cn"", """"), ""."", """"))), 0), not(in(trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, "","", """"), ""-"", """"), ""@"", """"), ""www."", """"), ""inc"", """"), "".com"", """"), "".cn"", """"), ""."", """")), ""-"", ""none"", ""no"", ""home"", ""n/a"", ""null"", ""unknown""))), 1)"
"    └─HashAgg_26","377832.95","root","","group by:Column#101, funcs:count(distinct Column#99)->Column#62, funcs:firstrow(Column#100)->gharchive_dev.github_users.organization"
"      └─Projection_53","377832.95","root","","gharchive_dev.github_events.actor_login, gharchive_dev.github_users.organization, trim(replace(replace(replace(replace(replace(replace(replace(replace(gharchive_dev.github_users.organization, ,, ), -, ), @, ), www., ), inc, ), .com, ), .cn, ), ., ))->Column#101"
"        └─IndexJoin_31","377832.95","root","","left outer join, inner:IndexLookUp_30, outer key:gharchive_dev.github_events.actor_login, inner key:gharchive_dev.github_users.login, equal cond:eq(gharchive_dev.github_events.actor_login, gharchive_dev.github_users.login)"
"          ├─IndexReader_49(Build)","472291.18","root","partition:watch_event","index:IndexRangeScan_48"
"          │ └─IndexRangeScan_48","472291.18","cop[tikv]","table:ge, index:index_ge_on_repo_id_type_action_created_at(repo_id, type, action, created_at, pr_merged, actor_login, number, push_distinct_size, push_size, additions, deletions)","range:[41986369 ""WatchEvent"",41986369 ""WatchEvent""], keep order:false"
"          └─IndexLookUp_30(Probe)","472291.18","root","",""
"            ├─IndexRangeScan_28(Build)","472291.18","cop[tikv]","table:gu, index:index_gu_on_login_is_bot_organization_country_code(login, is_bot, organization_formatted, country_code)","range: decided by [eq(gharchive_dev.github_users.login, gharchive_dev.github_events.actor_login)], keep order:false"
"            └─TableRowIDScan_29(Probe)","472291.18","cop[tikv]","table:gu","keep order:false"
