"id","estRows","task","access object","operator info"
"MergeJoin_36","29.66","root","","inner join, left key:Column#114, right key:Column#154"
"├─Sort_100(Build)","29.66","root","","Column#154"
"│ └─Projection_102","29.66","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#154, Column#153"
"│   └─Selection_104","29.66","root","","not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01"")))"
"│     └─HashAgg_113","37.07","root","","group by:Column#182, funcs:count(Column#183)->Column#153, funcs:firstrow(Column#184)->gharchive_dev.github_events.created_at"
"│       └─IndexReader_114","37.07","root","partition:pull_request_review_comment_event","index:HashAgg_106"
"│         └─HashAgg_106","37.07","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(1)->Column#183, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#184"
"│           └─IndexRangeScan_112","634.93","cop[tikv]","table:ge, index:index_ge_on_actor_id_type_action_created_at_repo_id_commits(actor_id, type, action, created_at, repo_id, push_distinct_size)","range:[5086433 ""PullRequestReviewCommentEvent"" ""created"",5086433 ""PullRequestReviewCommentEvent"" ""created""], keep order:false"
"└─Sort_66(Probe)","29.66","root","","Column#114"
"  └─Projection_68","29.66","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#114, Column#113"
"    └─Selection_70","29.66","root","","not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01"")))"
"      └─HashAgg_79","37.07","root","","group by:Column#169, funcs:count(Column#170)->Column#113, funcs:firstrow(Column#171)->gharchive_dev.github_events.created_at"
"        └─IndexReader_80","37.07","root","partition:pull_request_review_event","index:HashAgg_72"
"          └─HashAgg_72","37.07","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(1)->Column#170, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#171"
"            └─IndexRangeScan_78","634.93","cop[tikv]","table:ge, index:index_ge_on_actor_id_type_action_created_at_repo_id_commits(actor_id, type, action, created_at, repo_id, push_distinct_size)","range:[5086433 ""PullRequestReviewEvent"" ""created"",5086433 ""PullRequestReviewEvent"" ""created""], keep order:false"
