"id","estRows","task","access object","operator info"
"Projection_134","59.31","root","","Column#87, ifnull(Column#89, 0)->Column#92, ifnull(Column#91, 0)->Column#93"
"└─HashJoin_135","59.31","root","","left outer join, equal:[eq(Column#87, Column#90)]"
"  ├─Selection_148(Build)","23.73","root","","not(isnull(Column#90))"
"  │ └─CTEFullScan_149","29.66","root","CTE:issue_comments AS ic","data:CTE_1"
"  └─HashJoin_137(Probe)","59.31","root","","left outer join, equal:[eq(Column#87, Column#88)]"
"    ├─Selection_146(Build)","23.73","root","","not(isnull(Column#88))"
"    │ └─CTEFullScan_147","29.66","root","CTE:issues AS i","data:CTE_0"
"    └─HashAgg_140(Probe)","59.31","root","","group by:Column#87, funcs:firstrow(Column#87)->Column#87"
"      └─Union_141","59.31","root","",""
"        ├─Projection_142","29.66","root","","Column#83"
"        │ └─CTEFullScan_143","29.66","root","CTE:issues","data:CTE_0"
"        └─Projection_144","29.66","root","","Column#85"
"          └─CTEFullScan_145","29.66","root","CTE:issue_comments","data:CTE_1"
"CTE_1","29.66","root","","Non-Recursive CTE"
"└─Sort_92(Seed Part)","29.66","root","","Column#74"
"  └─Projection_94","29.66","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#74, Column#73"
"    └─Selection_96","29.66","root","","or(1, not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""))))"
"      └─HashAgg_105","37.07","root","","group by:Column#116, funcs:count(Column#117)->Column#73, funcs:firstrow(Column#118)->gharchive_dev.github_events.created_at"
"        └─IndexReader_106","37.07","root","partition:issue_comment_event","index:HashAgg_98"
"          └─HashAgg_98","37.07","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(1)->Column#117, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#118"
"            └─IndexRangeScan_104","634.93","cop[tikv]","table:ge, index:index_ge_on_actor_id_type_action_created_at_repo_id_commits(actor_id, type, action, created_at, repo_id, push_distinct_size)","range:[5086433 ""IssueCommentEvent"" ""created"",5086433 ""IssueCommentEvent"" ""created""], keep order:false"
"CTE_0","29.66","root","","Non-Recursive CTE"
"└─Sort_46(Seed Part)","29.66","root","","Column#36"
"  └─Projection_48","29.66","root","","date_format(gharchive_dev.github_events.created_at, %Y-%m-01)->Column#36, Column#35"
"    └─Selection_50","29.66","root","","or(1, not(isnull(date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""))))"
"      └─HashAgg_59","37.07","root","","group by:Column#99, funcs:count(Column#100)->Column#35, funcs:firstrow(Column#101)->gharchive_dev.github_events.created_at"
"        └─IndexReader_60","37.07","root","partition:issues_event","index:HashAgg_52"
"          └─HashAgg_52","37.07","cop[tikv]","","group by:date_format(gharchive_dev.github_events.created_at, ""%Y-%m-01""), funcs:count(1)->Column#100, funcs:firstrow(gharchive_dev.github_events.created_at)->Column#101"
"            └─IndexRangeScan_58","634.93","cop[tikv]","table:ge, index:index_ge_on_actor_id_type_action_created_at_repo_id_commits(actor_id, type, action, created_at, repo_id, push_distinct_size)","range:[5086433 ""IssuesEvent"" ""opened"",5086433 ""IssuesEvent"" ""opened""], keep order:false"
